### ISSUE TITLE
Resource files missing

### ISSUE THREAD

**Issue by AnaRadu24** [feng-yufei/Neural-Natural-Logic#2]
Could you provide the /data/utils file and the /results folder please? (/results/nnl_saved_model_snli-memory_module, ./results/esim_saved_model_snli-20200323-184427/esim_model.pt) Thank you.

**Comment by krishnamrith12** [comment]
Its available here
 https://github.com/feng-yufei/Neural-Natural-Logic/blob/main/utils/data/io.py
